### PR TITLE
Add separator detection in the connector

### PR DESCRIPTION
**Pull request by ZheSun88**
<work in progress> it can be reviewed, now.  further fixes are coming
Add separator detection in the connector
Add test cases for the reported locale issues

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76#-LDAw5hdEXV8zLRPORoM:-LDAw5hdEXV8zLRPORoN:b2sd8qm) (no related file):*
self block

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76)*

**Comment by ZheSun88** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76#-LDAw5hdEXV8zLRPORoM:-LDFgDxsEuPpnmt6z3_s:bnzvj4) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

still missing the test cases for setting sever side value. 
</blockquote></details>

Now it is ready to go 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76)*

**Comment by caalador** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 9 at r2](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76#-LDFiu4SCW05-DpqQYTO:-LDFiu4SCW05-DpqQYTP:b-tsn3rn) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/cce970fa4f018fe80f0d35bbf6f7d3155e04f5fa/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L9)):*
> ```JavaScript
> 
>         datepicker.$connector = {};
>         datepicker.$connector.oldLocale = "undefined";
> ```

just leave this undefined instead of setting string "undefined"; e.g. `datepicker.$connector.oldLocale`

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 53 at r2](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76#-LDFlc-ACL6VgYf55YMh:-LDFlc-ACL6VgYf55YMi:b-1fgvxg) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/cce970fa4f018fe80f0d35bbf6f7d3155e04f5fa/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L53)):*
> ```
>                 let sampleDate = new Date(sample);
>                 let sampleOldLocaleDate = sampleDate.toLocaleDateString(oldLocale);
> ```
this could be just `var targetLocaleDate =  new Date(sample).toLocaleDateString(oldLocale);`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 52 at r3](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76#-LDG-Z69CM7BeaaQp2KJ:-LDG-Z69CM7BeaaQp2KK:b-m2nsi4) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/aa775de488092d4a3ca3bfa3ee1504b8cb627162/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L52)):*
> ```JavaScript
>                 const sample_parts = sample.split(separator);
>                 let date;
>                 var targetLocaleDate = new Date(sample).toLocaleDateString(oldLocale);
> ```

This could still be a `let` or `const` as the value is not changed.
Also you could just grab the string on the same line and have a `const expectedDateString = new Date(sample).toLocalDateString(oldLocale).toString();`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76)*

**Comment by ZheSun88** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 52 at r3](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76#-LDG-Z69CM7BeaaQp2KJ:-LDG2GpA0RqsnPcN9ZeJ:bftbasf) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/aa775de488092d4a3ca3bfa3ee1504b8cb627162/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L52)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This could still be a `let` or `const` as the value is not changed.
Also you could just grab the string on the same line and have a `const expectedDateString = new Date(sample).toLocalDateString(oldLocale).toString();`
</blockquote></details>

you got it. :-)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/76)*

**Pull request merged**
