### PR TITLE
Make connector work with complicated separators

### LINKED ISSUE #105: DatePicker doesn't work with the Hungarian locale.
datepickerConnector fails to handle the date parsing for a 
DatePicker set into the Hungarian locale that uses the format `yyyy. MM. dd. `

The regexMatcher should probably be updated to:
`/[0-9]+(.)\s?[0-9]+\1\s?[0-9]+\1?/;` or `/[0-9]+(.\s?)[0-9]+\1[0-9]+\1?/`
but this only fixes the separator parsing but our sample doesn't take into account that we also
have the separator at the end of the string.

That again can be fixed with having the if check that `targetLocalDate.startsWith(sample)` then the possible ending separator can be there but wont fail the matching.

### PR DESCRIPTION
**Pull request by ZheSun88**
Fixes #105

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/106)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @ZheSun88)

---

*[src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleIT.java, line 52 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/106#-LG9XDFy5asYdvfG8-g1:-LG9XDFy5asYdvfG8-g2:bdjrhy0) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/b387bb27def8b0caf1b90c0cb4454ccaa8bcd5ff/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleIT.java#L52)):*
> ```Java
> 
>         Assert.assertEquals("There should not error in the console", 0,
>                 getLogEntries(Level.SEVERE).size());
> ```

`checkLogsForErrors()` instead of checking size for SEVERE.

---

*[src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java, line 41 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/106#-LG9WpxH-BnQsAuSMxTn:-LG9WpxH-BnQsAuSMxTo:bak3g4s) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/b387bb27def8b0caf1b90c0cb4454ccaa8bcd5ff/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java#L41)):*
> ```Java
>     }
> 
>     private void checkHungarianLocale() {
> ```

addHungarianLocale as it doesn't check anything.

---

*[src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java, line 46 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/106#-LG9WjlB3-OtnrzjNEtU:-LG9WjlB3-OtnrzjNEtV:b-cscpo6) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/b387bb27def8b0caf1b90c0cb4454ccaa8bcd5ff/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java#L46)):*
> ```Java
>         add(datePicker);
>     }
> }
> ```

Where did the new line go to?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/106)*

**Comment by caalador** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed, 3 unresolved discussions (waiting on @ZheSun88)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/106)*

**Comment by ZheSun88** [comment]
Review status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @caalador)

---

*[src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleIT.java, line 52 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/106#-LG9XDFy5asYdvfG8-g1:-LG9w3BP4DaW-s8t_VZB:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/b387bb27def8b0caf1b90c0cb4454ccaa8bcd5ff/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocaleIT.java#L52)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

`checkLogsForErrors()` instead of checking size for SEVERE.
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java, line 41 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/106#-LG9WpxH-BnQsAuSMxTn:-LG9xpc25U3h9PsQguBw:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/b387bb27def8b0caf1b90c0cb4454ccaa8bcd5ff/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java#L41)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

addHungarianLocale as it doesn't check anything.
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java, line 46 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/106#-LG9WjlB3-OtnrzjNEtU:-LG9w3fb53sHmTMJNb7U:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/b387bb27def8b0caf1b90c0cb4454ccaa8bcd5ff/src/test/java/com/vaadin/flow/component/datepicker/DatePickerLocalePage.java#L46)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Where did the new line go to?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/106)*

**Comment by caalador** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/106)*

**Pull request merged**
