### PR TITLE
Update generated code

### PR DESCRIPTION
**Pull request by ZheSun88**
fix after vaadin/flow#3678

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/44)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/44#-:-L7Ysn1Yp7DLK8fvjNTg:bnfp4nl)*

**Comment by gilberto-torrezan** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/44#-:-L7YswOozV3Ar1BcMk9H:b8b79qu)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 257 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/44#-L7Yt0O_PYj3CcYlC5ad:-L7Yt0O_PYj3CcYlC5ae:bhbhp49) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/155847c334ef3de1df31149bae372e8d931468c8/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L257)):*
> ```Java
>      * @param i18n
>      *            the internationalized properties, not <code>null</code>
>      * @return this instance for method chaining
> ```

It doesn't return anything anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/44)*

**Comment by ZheSun88** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 257 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/44#-L7Yt0O_PYj3CcYlC5ad:-L7YtLP9N4K708_z0U-Z:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/155847c334ef3de1df31149bae372e8d931468c8/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L257)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

It doesn't return anything anymore.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/44)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/44#-:-L7YtLMKsrQD542fTGJf:bnfp4nl)*

**Pull request merged**
