### PR TITLE
Add open() and close() methods and update the property synchronously

### PR DESCRIPTION
**Pull request by pekam**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/48)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/48#-L81Jxq6AEQ5fcarMOvR:-L81Jxq6AEQ5fcarMOvS:bmomds7) (no related file):*
An IT test to check that the drop-down is actually open would be good to have.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/48)*

**Comment by pekam** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/48#-L81Jxq6AEQ5fcarMOvR:-L81aNeh7Xg4tjZTK3N9:bb7f2mf) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

An IT test to check that the drop-down is actually open would be good to have.
</blockquote></details>

done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/48)*

**Comment by caalador** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 498 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/48#-L81pwRY24VqSCiNSilB:-L81pwRY24VqSCiNSilC:b-6wtnxg) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/515a40d081e9b5f4df9a80e4f62d6b87301c5029/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L498)):*
> ```Java
> 
>         // To update the server-side property synchronously
>         super.setOpened(false);
> ```

is this needed? does the client side set it automatically on function call open/close if it is it's marked synchronize 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/48)*

**Comment by pekam** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 498 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/48#-L81pwRY24VqSCiNSilB:-L81rahYBPmaQn1AP7dJ:bc4oedx) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/515a40d081e9b5f4df9a80e4f62d6b87301c5029/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L498)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

is this needed? does the client side set it automatically on function call open/close if it is it's marked synchronize 
</blockquote></details>

Without this, we only call `close()` on the client-side. The `opened`-property is synchronized, so we do get the updated value from client to server after the JS function has updated it.

But that would be asynchronous, so in the server-side calling `isOpened()` immediately after `close()` would return `true`, which is incorrect. That's why we update the property here, to have immediately correct value for the server-side property.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/48)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/48#-:-L826IZ0CeRzNuNgzDlB:bnfp4nl)*

**Pull request merged**
