### PR TITLE
Fix I18n setting for DatePicker

### LINKED ISSUE #88: DatePickerI18n is not working
Hello,

I've just clone the repository and run "mvn jetty:run -PrunTests".
The "Internationalized date picker" case is not working (and there is no error during the tests).
See screenshot below. Perhaps it has been introduced in RC1 (on beta 10 it was working).

capture du 2018-06-04 13-59-27

Thanks

### PR DESCRIPTION
**Pull request by ZheSun88**
Add test case;
Fix #88

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/91)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/91#-LEJQCC84pESX672Y8AN:-LEJQCC84pESX672Y8AO:b89gp54) (no related file):*
Same questions as for upload: does the test fail with the previous state of the code and what was wrong with the code ?

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 53 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/91#-LEJQ-Bu0WzHVDxa_6Dr:-LEJQ-Bv3iSdrKWx8ID7:bj0qkxt) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/d07f0caf12d22c80c1c4b68173e2288ddf02b62c/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L53)):*
> ```
> DatePickerI18n i18n;
> ```

`private` 

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 310 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/91#-LEJQ6lm2gwDgm4QQDFs:-LEJQ6lm2gwDgm4QQDFt:b-ftkfyu) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/d07f0caf12d22c80c1c4b68173e2288ddf02b62c/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L310)):*
> ```
> JsonObject i18nObject = (JsonObject) JsonSerializer.toJson(i18n);
> ```

Same comment as for `Upload`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/91)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/91#-LEJQCC84pESX672Y8AN:-LEJaY8j4nf5VJmsNg48:bs1ymy4) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Same questions as for upload: does the test fail with the previous state of the code and what was wrong with the code ?
</blockquote></details>

The test tested only the server-side result and didn't check the actual text show on the client component.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/91)*

**Comment by ZheSun88** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 53 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/91#-LEJQ-Bu0WzHVDxa_6Dr:-LEJaQkV99kFviRaYI4l:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/d07f0caf12d22c80c1c4b68173e2288ddf02b62c/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> DatePickerI18n i18n;
> ```

`private` 
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 310 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/91#-LEJQ6lm2gwDgm4QQDFs:-LEJaRJLEBkA7TDNN2Ir:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/d07f0caf12d22c80c1c4b68173e2288ddf02b62c/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L310)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> JsonObject i18nObject = (JsonObject) JsonSerializer.toJson(i18n);
> ```

Same comment as for `Upload`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/91)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/91#-:-LEJp54V2VJBhyXW15gB:bnfp4nl)*

**Pull request merged**
