### PR TITLE
Add DatePicker IT test

### PR DESCRIPTION
**Pull request by ZheSun88**
add DatePicker IT test class;
add dependency to Pom

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/8)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/ui/datepicker/DatePickerIT.java, line 139 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/8#-KxroPswJ53miVNvEBu0:-KxroPswJ53miVNvEBu1:bgnkofy) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/c88802ba44f23702512fdbc55cf6fa8a52dc895d/src/test/java/com/vaadin/ui/datepicker/DatePickerIT.java#L139)):*
> protected String getTestPath() {
> 
>         return "/";
> 
>     }

Do you need to override this method each time ?
Wouldn't it be better to implement it in this way in the `ComponentDemoTest` class if it's not yet done ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/8)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/ui/datepicker/DatePickerIT.java, line 139 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/8#-KxroPswJ53miVNvEBu0:-Kxrp5DDtzko5y36Padp:b-op4uxt) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/c88802ba44f23702512fdbc55cf6fa8a52dc895d/src/test/java/com/vaadin/ui/datepicker/DatePickerIT.java#L139)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> protected String getTestPath() {
> 
>         return "/";
> 
>     }

Do you need to override this method each time ?
Wouldn't it be better to implement it in this way in the `ComponentDemoTest` class if it's not yet done ?
</blockquote></details>

yes, that would be great.. I will work on that after i test all the component. thanks for reminding me. 

there should be two conditions:
when there is parameter, the `getTestPath()` will use the parameter, like for textfield and ordered layout;
when there is no parameter, the `getTestPath` will use the default `"/"`

do i understand that correctly?
 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/8)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/ui/datepicker/DatePickerIT.java, line 139 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/8#-KxroPswJ53miVNvEBu0:-KxrqFrip82OYIYLspsW:bcbrkre) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/c88802ba44f23702512fdbc55cf6fa8a52dc895d/src/test/java/com/vaadin/ui/datepicker/DatePickerIT.java#L139)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

yes, that would be great.. I will work on that after i test all the component. thanks for reminding me. 

there should be two conditions:
when there is parameter, the `getTestPath()` will use the parameter, like for textfield and ordered layout;
when there is no parameter, the `getTestPath` will use the default `"/"`

do i understand that correctly?
 
</blockquote></details>

Which parameter you mean ?

The simplest thing: it should return "/" in the super implementation.
That's enough.

You will override it in subclass each time when you need it.

If you may even improve this somehow then it will be even better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/8)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/ui/datepicker/DatePickerIT.java, line 139 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/8#-KxroPswJ53miVNvEBu0:-Kxrr8NOUFLg2nne6LQt:bxiuy26) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/c88802ba44f23702512fdbc55cf6fa8a52dc895d/src/test/java/com/vaadin/ui/datepicker/DatePickerIT.java#L139)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Which parameter you mean ?

The simplest thing: it should return "/" in the super implementation.
That's enough.

You will override it in subclass each time when you need it.

If you may even improve this somehow then it will be even better.
</blockquote></details>

oh, okay, i see...thanks.. working on that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/8)*

**Comment by ZheSun88** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/ui/datepicker/DatePickerIT.java, line 139 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/8#-KxroPswJ53miVNvEBu0:-KxrxTnRCiu6Yi6RMCNG:b-g7j6x5) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/c88802ba44f23702512fdbc55cf6fa8a52dc895d/src/test/java/com/vaadin/ui/datepicker/DatePickerIT.java#L139)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

oh, okay, i see...thanks.. working on that
</blockquote></details>

yes, new version pushed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/8)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/8)*

**Pull request merged**
