### PR TITLE
Implement setLocale() method to support different date format

### PR DESCRIPTION
**Pull request by ZheSun88**
add connector.js for formatDate and parseDate

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Test related to this issue will be added after review.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/51#-:-L8X3f8xG1Nd2Y2ArW1P:b-lhyx8f)*

**Comment by ZheSun88** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/51#-L8X3o6JqHMc3_V4u9I8:-L8X3o6JqHMc3_V4u9I9:b-9ahzsh) (no related file):*
need test class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8X3o6JqHMc3_V4u9I8:-L8a4EswD3kZ49c5JkVT:b-mubzkj) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

need test class
</blockquote></details>

I would like to see also a case when "locale is unsupported".

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 251 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8a1qZv-RmHo5h7nOGw:-L8a1qZv-RmHo5h7nOGx:b-2onkky) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/8dbde0426ebe4abb7e698662c01b4bb9950fe143/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L251)):*
> a 

What is `a` ?
No one letter variables please.

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 17 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8a2iquBUGen1alBVvv:-L8a2iquBUGen1alBVvw:b-10nf8r) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/8dbde0426ebe4abb7e698662c01b4bb9950fe143/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L17)):*
> throw new RangeError("The locale is not supported.");

So if the user browser doesn't support locale then he won't be able to use the date-picker component at all?
It doesn't sound right.
It's not a developer mistake where an exception is fine since he should fix it.
I think it should fallback to the default behavior instead of throwing and just log a warning about impossibility to use locale.

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 21 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8a3N_06u5Tw4GYAGVT:-L8a3N_06u5Tw4GYAGVU:bc9pryf) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/8dbde0426ebe4abb7e698662c01b4bb9950fe143/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L21)):*
> d 

No one letter variables please even in JS.

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 26 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8a3UhE3f9OQuzlqa-b:-L8a3UhE3f9OQuzlqa-c:bqhx99q) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/8dbde0426ebe4abb7e698662c01b4bb9950fe143/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L26)):*
> sp

What does mean `sp` ?

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 30 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8a3a1h7reb_1NVUHm9:-L8a3a1h7reb_1NVUHmA:buer8ty) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/8dbde0426ebe4abb7e698662c01b4bb9950fe143/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L30)):*
> ```JavaScript
>                 var date = new Date();
>                 var sample = new Date(sp);
>                 var sample2 = sample.toLocaleDateString(locale);
> ```

`sample2` ?
What does it mean ?

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 43 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8a3oxOArlNwqV9e0fp:-L8a3oxOArlNwqV9e0fq:b-31c1jy) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/8dbde0426ebe4abb7e698662c01b4bb9950fe143/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L43)):*
> throw ("Selected locale is using unsupported date format.");

Again it throws .
Is it correct ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by ZheSun88** [comment]
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8X3o6JqHMc3_V4u9I8:-L8a52FX5CJrMCmFEV-m:b-gt64yf) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I would like to see also a case when "locale is unsupported".
</blockquote></details>

Yep, this will be included in the test class. thanks for reminding me

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 251 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8a1qZv-RmHo5h7nOGw:-L8a5B4y1ytePTD_mRir:bb3zeow) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/8dbde0426ebe4abb7e698662c01b4bb9950fe143/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L251)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> a 

What is `a` ?
No one letter variables please.
</blockquote></details>

i will rename this variable, sorry for that.

this parameter is used for the js method `toLocaleDateString()` as languageTag

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 17 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8a2iquBUGen1alBVvv:-L8a5ZVw50ejIcfx9fGJ:b-578dmz) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/8dbde0426ebe4abb7e698662c01b4bb9950fe143/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L17)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> throw new RangeError("The locale is not supported.");

So if the user browser doesn't support locale then he won't be able to use the date-picker component at all?
It doesn't sound right.
It's not a developer mistake where an exception is fine since he should fix it.
I think it should fallback to the default behavior instead of throwing and just log a warning about impossibility to use locale.
</blockquote></details>

Yes, i think you are correct on this, I think fallback to a default one is more reasonable and log a warning in the console. 

pls, the empty space will be removed together with next commit

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 21 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8a3N_06u5Tw4GYAGVT:-L8aSmr-4_qf_kMglh_5:b-hff6wv) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/8dbde0426ebe4abb7e698662c01b4bb9950fe143/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L21)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> d 

No one letter variables please even in JS.
</blockquote></details>

renamed

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 26 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8a3UhE3f9OQuzlqa-b:-L8a63WGD8-f23imW84-:b-iv6c2w) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/8dbde0426ebe4abb7e698662c01b4bb9950fe143/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L26)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> sp

What does mean `sp` ?
</blockquote></details>

I will rename this variable. 
The usage of these sample is to decided which date format we should use to parse the string based on the locale. 

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 30 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8a3a1h7reb_1NVUHm9:-L8aSot90otovstk7u1K:b-hff6wv) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/8dbde0426ebe4abb7e698662c01b4bb9950fe143/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L30)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`sample2` ?
What does it mean ?


</blockquote></details>

renamed

---

*[src/main/resources/META-INF/resources/frontend/datepickerConnector.js, line 43 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8a3oxOArlNwqV9e0fp:-L8aSs3x70CAmY90h-AH:bxd2txv) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/8dbde0426ebe4abb7e698662c01b4bb9950fe143/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L43)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> throw ("Selected locale is using unsupported date format.");

Again it throws .
Is it correct ?
</blockquote></details>

changed it to a warning.

But i think there must be some better way from you, ;-) 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by ZheSun88** [comment]
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8X3o6JqHMc3_V4u9I8:-L8bCQX96fbJoXfAX71F:bps8y5b) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Yep, this will be included in the test class. thanks for reminding me
</blockquote></details>

@denis-anisimov  now test classes are there. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by denis-anisimov** [comment]
Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 74 at r5](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8bJwhYDt8eQuHEphdd:-L8bJwhYDt8eQuHEphde:bar51tc) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/815b95205131b9b442bc36faa8ec72d301d27560/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L74)):*
> getElement().getNode()
>                 .runWhenAttached(ui -> setLocale(UI.getCurrent().getLocale()));

Could it be done in `initConnector()` method which is also executed on attache event?

Also is it correct call at all?
The `setLocale` will be executed when the node is attached.
So if the developer sets the locale before attaching the node then it will be overridden by the UI locale.
(may be the call should not be done when the element is attached but rather right away)

If you don't want to give a control over the locale to the developer then make `setLocale` `private`.

---

*[src/test/java/com/vaadin/flow/component/datepicker/demo/DatePickerView.java, line 206 at r5](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8bL1ToEjdg8JjdGYf8:-L8bL1ToEjdg8JjdGYf9:b-w0w49x) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/815b95205131b9b442bc36faa8ec72d301d27560/src/test/java/com/vaadin/flow/component/datepicker/demo/DatePickerView.java#L206)):*
> Type1

Sorry that I missed that from the very beginning.
Don't use variables with first letter in upper case.
Use camel case.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 74 at r5](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8bJwhYDt8eQuHEphdd:-L8bQZfv48C7tmG1ocfQ:br23mmo) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/815b95205131b9b442bc36faa8ec72d301d27560/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L74)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> getElement().getNode()
>                 .runWhenAttached(ui -> setLocale(UI.getCurrent().getLocale()));

Could it be done in `initConnector()` method which is also executed on attache event?

Also is it correct call at all?
The `setLocale` will be executed when the node is attached.
So if the developer sets the locale before attaching the node then it will be overridden by the UI locale.
(may be the call should not be done when the element is attached but rather right away)

If you don't want to give a control over the locale to the developer then make `setLocale` `private`.
</blockquote></details>

The idea is using the UI locale by default, if the user don't set a customized locale. in this case, What would be a proper way to do that? 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by ZheSun88** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 74 at r5](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8bJwhYDt8eQuHEphdd:-L8bSucYBc-2oYcf2RQt:b-jlq4yk) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/815b95205131b9b442bc36faa8ec72d301d27560/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L74)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

The idea is using the UI locale by default, if the user don't set a customized locale. in this case, What would be a proper way to do that? 
</blockquote></details>

moved it to the `initConnector`. 

---

*[src/test/java/com/vaadin/flow/component/datepicker/demo/DatePickerView.java, line 206 at r5](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8bL1ToEjdg8JjdGYf8:-L8bSlAM69HhURAWEFKu:bslj05o) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/815b95205131b9b442bc36faa8ec72d301d27560/src/test/java/com/vaadin/flow/component/datepicker/demo/DatePickerView.java#L206)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Type1

Sorry that I missed that from the very beginning.
Don't use variables with first letter in upper case.
Use camel case.
</blockquote></details>

oh, sorry, i will remember that.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 263 at r6](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8bU-Nw5FH-T6UDEuVq:-L8bU-Nw5FH-T6UDEuVr:b-3e8xxk) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/c4f4713793dd55bf36369b41b079cbf2182e0201/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L263)):*
> setLocale(UI.getCurrent().getLocale());

As I said: I understand the intention but the implementation is wrong.

You have two options:
- either set the locale inside CTOR (without waiting for attach) directly. You use `UI.getCurrent()` anyway. Then why do you need to wait attaching ?
- or check whether the current locale in `DatePicker` is `null`  and then set `UI` locale . But then you will need a variable where locale is stored.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 263 at r6](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8bU-Nw5FH-T6UDEuVq:-L8bVXfs3AzoFQ89fTeE:bmac7ti) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/c4f4713793dd55bf36369b41b079cbf2182e0201/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L263)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> setLocale(UI.getCurrent().getLocale());

As I said: I understand the intention but the implementation is wrong.

You have two options:
- either set the locale inside CTOR (without waiting for attach) directly. You use `UI.getCurrent()` anyway. Then why do you need to wait attaching ?
- or check whether the current locale in `DatePicker` is `null`  and then set `UI` locale . But then you will need a variable where locale is stored.
</blockquote></details>

for the first option, as I understand, if i set the locale directly in the CTOR, the Unit test will fail immediately,  Because there is no UI when running it. That is why i added the `runWhenAttached`.. I think right now, it is about solving the same issue. 

in this case, should i consider the 2nd option?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 263 at r6](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8bU-Nw5FH-T6UDEuVq:-L8bfRw1Ad56BXqmdqI8:ba8zaz7) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/c4f4713793dd55bf36369b41b079cbf2182e0201/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L263)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

for the first option, as I understand, if i set the locale directly in the CTOR, the Unit test will fail immediately,  Because there is no UI when running it. That is why i added the `runWhenAttached`.. I think right now, it is about solving the same issue. 

in this case, should i consider the 2nd option?

</blockquote></details>

Just set the locale before executing the test. Via the UI.setCurrent() method.
Don't forget to reset it after the test.
And make a test `@NotThreadSafe`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 263 at r6](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8bU-Nw5FH-T6UDEuVq:-L8bfeFf2Y0tV_OQtedw:b90fcma) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/c4f4713793dd55bf36369b41b079cbf2182e0201/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L263)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Just set the locale before executing the test. Via the UI.setCurrent() method.
Don't forget to reset it after the test.
And make a test `@NotThreadSafe`.
</blockquote></details>

Crap.
Not the locale.
Set the `UI` before the test.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by ZheSun88** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 263 at r6](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-L8bU-Nw5FH-T6UDEuVq:-L8bj_tl370OflZA0ESV:btng5ti) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/c4f4713793dd55bf36369b41b079cbf2182e0201/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L263)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Crap.
Not the locale.
Set the `UI` before the test.
</blockquote></details>

Okay, Thank you so much. 

set the method to CTOR and modified the tests. :+1: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker-flow/51#-:-L8bmApd6aGn0P_emC4-:bnfp4nl)*

**Pull request merged**
