### PR TITLE
Refactor the code in demo and add more tests

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/78)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java, line 168 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/78#-LDGbq447fb9ZSDZAQR1:-LDGbq447fb9ZSDZAQR2:b-yegmow) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/6ab07d4d1bfc0e8cae72811e9d09e70c76cbce26/src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java#L168)):*
> ```
>  Assert.assertEquals
> ```

Use `assertTrue` instead (if the return value is really boolean).
Just cast the result to `boolean`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/78#-:-LDGcDiw0jd_HmvwKSJw:bnfp4nl)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java, line 168 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/78#-LDGbq447fb9ZSDZAQR1:-LDGeInoCO_3IlQOVvQ1:b-s2x6fb) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/6ab07d4d1bfc0e8cae72811e9d09e70c76cbce26/src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java#L168)):*
> ```
>  Assert.assertEquals
> ```
I think we are using this in all the test cases... should i change all of them in this case?? what is the difference between this two?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/78)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java, line 168 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/78#-LDGbq447fb9ZSDZAQR1:-LDGfczQE88KisQkOYVq:b-u936vg) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/6ab07d4d1bfc0e8cae72811e9d09e70c76cbce26/src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java#L168)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> ```
>  Assert.assertEquals
> ```
I think we are using this in all the test cases... should i change all of them in this case?? what is the difference between this two?
</blockquote></details>

Logically there is no difference.
But you will get more meaningful error message when it fails.
Changes in other places may be done separately since they are not related to the current PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/78)*

**Comment by ZheSun88** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java, line 168 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/78#-LDGbq447fb9ZSDZAQR1:-LDGjOz24MKK53pWRnbG:b-7rl0jr) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/6ab07d4d1bfc0e8cae72811e9d09e70c76cbce26/src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java#L168)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Logically there is no difference.
But you will get more meaningful error message when it fails.
Changes in other places may be done separately since they are not related to the current PR.
</blockquote></details>

done 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/78)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/78#-:-LDGjq1BCC3YqafKl8DX:bnfp4nl)*

**Pull request merged**
