### PR TITLE
Replace HasValue with AbstractSinglePropertyField

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 61 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67#-LAx24B62kd640w3eQIR:-LAx24B787KW3-d7Hl1U:b-241cta) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/01a652550bad8979d76af94fffc2495d88b64af7/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L61)):*
> ```Java
>         return d == null ? "" : d.toString();
>     };
> ```

`parser` and `formatter`  should be constants.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 77 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67#-LAx2ii5EiuIHwthQfnT:-LAx2ii5EiuIHwthQfnU:br98mts) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/01a652550bad8979d76af94fffc2495d88b64af7/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L77)):*
> ```Java
>      * @see #setValue(LocalDate)
>      */
>     public DatePicker(LocalDate initialDate) {
> ```

Is the `initialDate` being set?

---

*[src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java, line 66 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67#-LAx2u1q4eSwGIkq88Bf:-LAx2u1q4eSwGIkq88Bg:bykpvnp) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/01a652550bad8979d76af94fffc2495d88b64af7/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java#L66)):*
> ```Java
>         // https://github.com/vaadin/flow/issues/3994
>         picker.getElement().setProperty("value", null);
>         Assert.assertEquals(null, picker.getValue());
> ```

Missing a unit test for the non-default CTOR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 61 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67#-LAx24B62kd640w3eQIR:-LAxHDzmEt5-Lkh_JRqU:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/01a652550bad8979d76af94fffc2495d88b64af7/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L61)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`parser` and `formatter`  should be constants.
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java, line 77 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67#-LAx2ii5EiuIHwthQfnT:-LAxGyax-X4DzxexSaY9:b-lqft7z) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/01a652550bad8979d76af94fffc2495d88b64af7/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L77)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Is the `initialDate` being set?
</blockquote></details>

Nope, fixed.

Also needed to add a workaround for updating presentation value which is not updated in super class

---

*[src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java, line 66 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67#-LAx2u1q4eSwGIkq88Bf:-LAxHCUX4c6hEPKCDgaQ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker-flow/blob/01a652550bad8979d76af94fffc2495d88b64af7/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java#L66)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Missing a unit test for the non-default CTOR.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67)*

**Comment by gilberto-torrezan** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67#-LB-dqPB9wGKLzjzlhYV:-LB-dqPB9wGKLzjzlhYW:b-oq1a8d) (no related file):*
Blocking this from being merged until the code generator is updated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker-flow/67)*

**Pull request merged**
